language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
script:
  - pylint devourer --rcfile=.pylintrc
  - coverage run --source=devourer -m devourer.tests && coverage report -m
  - cd docs && make html